USE shalom_cnd;
SET character_set_client = utf8;
TRUNCATE TABLE dependents;
INSERT INTO dependents (`nip`, `relation`, `nom`, `prenom`, `age`, `sexe`) VALUES (71,"Demandeur","BERKOUN","Lailla",null,"F"),
(71,"Conjoint","HAIDRA","Youssef",null,"M"),
(71,"Autre","BELBACHIR","Mohamed (20)",null,"M"),
(71,"Enfant",null,"Lyna Serine","10","F"),
(71,"Enfant",null,"Abderahmane","12","M"),
(71,"Enfant",null,"Ritadj Radja","06","F"),
(71,"Enfant",null,"Naidra","02","M"),
(72,"Demandeur","AATIFI","Bouchra",null,"F"),
(72,"Conjoint","YASSINE","Mohamed",null,"M"),
(72,"Enfant",null,"Youssef","11","M"),
(72,"Enfant",null,"Marwa","08","F"),
(73,"Demandeur","JOSEPH","Lisana",null,"F"),
(73,"Conjoint","FUMERLUS","Lous-Fils",null,"M"),
(73,"Enfant",null,"Lawanda","10","F"),
(73,"Enfant",null,"Daphnia","16","F"),
(73,"Enfant",null,"Jeremiah","04","M"),
(73,"Enfant",null,"Ciaire","9 mois","F"),
(77,"Demandeur","KOUROUMA","Mariam",null,"F"),
(77,"Enfant",null,"Lancine","08","F"),
(77,"Enfant",null,"Ahmed","17","M"),
(74,"Demandeur","CHEDDAD","Sokayna",null,"F"),
(74,"Conjoint","MARJOUD","Rachid",null,"M"),
(74,"Enfant",null,"Rayane","10","M"),
(74,"Enfant",null,"Ziad","05","M"),
(74,"Enfant",null,"Comassan","01","M"),
(69,"Demandeur","DEADA","Rosine-Estelle",null,"F"),
(69,"Enfant",null,"Siaho Marie V","13","F"),
(69,"Enfant",null,"Ange Henock","11","M"),
(69,"Enfant",null,"Emmanuel","03","M"),
(78,"Demandeur","GUNANAJAKAM","Primadharshini",null,"F"),
(78,"Conjoint","NAGARAJAH","Rayeendikajah",null,"M"),
(78,"Enfant",null,"Iniyavan","13","M"),
(78,"Enfant",null,"Haniyavan","10","M"),
(78,"Enfant",null,"Nitharsana","06","F"),
(75,"Demandeur","ESWARAN","Tharsini",null,"F"),
(75,"Conjoint","KIDDINAPILLAI","Eswaran",null,"M"),
(75,"Enfant",null,"Thivansham","11","M"),
(75,"Enfant",null,"Tilakkshah","13","M"),
(75,"Enfant",null,"Kailash","09","M"),
(75,"Enfant",null,"Liyana","07","F"),
(75,"Enfant",null,"Mantha","04","F"),
(79,"Demandeur","SEENITHAMBY","Thanuja",null,"F"),
(79,"Conjoint","PALASUBRAMANIAM","Kantharaj",null,"M"),
(79,"Enfant",null,"Thelas","06","M"),
(79,"Enfant",null,"Ashaale","04","F"),
(82,"Demandeur","VELUPILLAI","Anusoosai",null,"F"),
(82,"Conjoint","BALASINGAM","Thiruchelvam",null,"M"),
(82,"Enfant",null,"Sanchana","12","F"),
(82,"Enfant",null,"Shakammam","11","M"),
(82,"Enfant",null,"Shaharna","08","F"),
(80,"Demandeur","SIVARASALINGAM","Santhanaladchum",null,"F"),
(80,"Enfant",null,"Vesnekam","11","M"),
(80,"Enfant",null,"Aisnega","12","F"),
(81,"Demandeur","BALASUBRAMANIAM","Niransala",null,"F"),
(81,"Autre","CUMARASAMY","Annaladchumy (mère,78)",null,""),
(81,"Enfant",null,"Prissha","13","F"),
(81,"Enfant",null,"Gershon","05","M"),
(90,"Demandeur","MAHENDRARAJAH","Janani",null,"F"),
(90,"Conjoint","SRISKANTHARAJAH","Yogaraj",null,"M"),
(90,"Enfant",null,"Shayana","08","F"),
(90,"Enfant",null,"Saraniya","12","F"),
(90,"Enfant",null,"Sachin","05","M"),
(88,"Demandeur","SINNATHAMBY","Sivajini",null,"F"),
(88,"Conjoint","THIRUCHELVAN","Ramesh",null,"M"),
(88,"Autre","MITHUSHAA","(fille 18)",null,"F"),
(88,"Enfant",null,"Hishani","15","F"),
(88,"Enfant",null,"Ahisham","08","M"),
(83,"Demandeur","SUBRAMANIAM","Kalaivani",null,"F"),
(83,"Conjoint","SIVARAJAH","Sivaransan",null,"M"),
(83,"Enfant",null,"Kamshiga","10","F"),
(83,"Enfant",null,"Siyaniga","05","F"),
(84,"Demandeur","THANKARASA","Thevi",null,"F"),
(84,"Conjoint","THANGATHANKATHURAI","Vasanth",null,"M"),
(84,"Enfant",null,"Nikitha","16","F"),
(84,"Enfant",null,"Neka","09","F"),
(84,"Enfant",null,"Niveen","05","M"),
(89,"Demandeur","SANTHALINGAM","Seevamala",null,"F"),
(89,"Conjoint","SELLATHURAI","Sivakumar",null,"M"),
(89,"Enfant",null,"Thissaan","10","M"),
(89,"Enfant",null,"Thilasksi","12","F"),
(89,"Enfant",null,"Thushalini","08","F"),
(89,"Enfant",null,"Saheeth","01","M"),
(76,"Demandeur","YOGANATHAN","Nanthini",null,"F"),
(76,"Conjoint","VELMURUGU","Yopanathan",null,"M"),
(76,"Enfant",null,"Thilothamy","13","F"),
(76,"Enfant",null,"Thanadchana","10","M"),
(91,"Demandeur","EASWARTHAS","Tharsini",null,"F"),
(91,"Conjoint","SHANMUGARAJAH","Nimalarajah",null,"M"),
(91,"Enfant",null,"Athavan","15","M"),
(91,"Enfant",null,"Kavijan","09","M"),
(85,"Demandeur","SINNARASA","Sukirtha",null,"F"),
(85,"Conjoint","SIVAPATHAM","Shamnukathason",null,"M"),
(85,"Enfant",null,"Sajinth","08","M"),
(85,"Enfant",null,"Santhos","06","M"),
(85,"Enfant",null,"Sivanusha","07","F"),
(92,"Demandeur","SLIMANI","Wahiba",null,"F"),
(92,"Conjoint","FODIL","Tamime",null,"M"),
(92,"Enfant",null,"Wassim","13","M"),
(92,"Enfant",null,"Iness","10","F"),
(92,"Enfant",null,"Insaf","08","F"),
(92,"Enfant",null,"Tasnine","05","F"),
(86,"Demandeur","YATCADI","Meryem",null,"M"),
(86,"Conjoint","HAMMOUCH","Rachid",null,"F"),
(86,"Enfant",null,"Taha","6 mois","M"),
(86,"Enfant",null,"Fatima","06","F"),
(86,"Enfant",null,"Othman","07","M"),
(134,"Demandeur","EL HAJJIOUI","Nadia",null,"F"),
(134,"Conjoint","CHAKROUNE","Zoubair",null,"M"),
(134,"Enfant",null,"Mohamed","09","M"),
(134,"Enfant",null,"Adam","05","M"),
(95,"Demandeur","MARTEL YALLICO","Carmen Rosa",null,"F"),
(95,"Enfant",null,"Isabelle","02","F"),
(95,"Enfant",null,"Marinella","06","F"),
(95,"Enfant",null,"Camille","12","F"),
(95,"Enfant",null,"Leonella","14","F"),
(96,"Demandeur","BENAHMED","Karima",null,"F"),
(96,"Conjoint","BOUHAL","Kamel",null,"M"),
(96,"Enfant",null,"Sofia?","06","F"),
(96,"Enfant",null,"Katia","08","F"),
(96,"Enfant",null,"Adam","02","M"),
(93,"Demandeur","DAHMANE","Ismahane",null,"F"),
(93,"Conjoint","ROUANI","Mohamed",null,"M"),
(93,"Enfant",null,"Nihal","12","F"),
(93,"Enfant",null,"Aicha","08","F"),
(94,"Demandeur","NAGALING","Vanaja",null,"F"),
(94,"Conjoint","VADIVELU","Vijendran",null,"M"),
(94,"Enfant",null,"Vikesh","12","M"),
(94,"Enfant",null,"Varsha","15","F"),
(98,"Demandeur","LAHMITI","Imane",null,"F"),
(98,"Conjoint","DAHMOUNI","Hamza",null,"M"),
(98,"Enfant",null,"Kinan","08","M"),
(98,"Enfant",null,"Rayan","10","M"),
(98,"Enfant",null,"Norane","05","F"),
(97,"Demandeur","EL MUSTAFA","Bassam",null,"F"),
(97,"Conjoint","ALTAMAN","Nehal",null,"M"),
(97,"Enfant",null,"Eleanora","02","F"),
(97,"Enfant",null,"Ilan","09","M"),
(99,"Demandeur","DAOUD","Hanane",null,"F"),
(99,"Conjoint","GOHTARI","Yazid",null,"M"),
(99,"Enfant",null,"Ilias","09","M"),
(99,"Enfant",null,"Amine","04","M"),
(100,"Demandeur","ADARDOU","Latifa",null,"F"),
(100,"Conjoint","AIT-RAMI","Driss",null,"M"),
(100,"Enfant",null,"Rumaysa","06","F"),
(100,"Enfant",null,"Imrane","09","M"),
(100,"Enfant",null,"Salman","08","M"),
(100,"Enfant",null,"Safouan","01","M"),
(101,"Demandeur","BOUIGUISSE","Khadija",null,"F"),
(101,"Enfant",null,"Sarah","15","F"),
(101,"Enfant",null,"Nour","13","F"),
(87,"Demandeur","EL MAALI","Sara",null,"F"),
(87,"Conjoint","BAHMOUCH","Rachid",null,"M"),
(87,"Enfant",null,"Assia","03","F"),
(87,"Enfant",null,"Mariam","08","F"),
(102,"Demandeur","NAVARETNARAJAH","Kirupthika",null,"F"),
(102,"Conjoint","MANICKARAJAH","Kisokumar",null,"M"),
(102,"Enfant",null,"Vithushan","07","M"),
(102,"Enfant",null,"Varsha","04","F"),
(104,"Demandeur","SINNATHAMBY","Kamala Pooshany",null,"F"),
(104,"Conjoint","VINASITHAMBY","Senthiel Natnan",null,"M"),
(104,"Enfant",null,"Vithujan","08","M"),
(104,"Enfant",null,"Sitharukesan","12","M"),
(63,"Demandeur","IGNATIUS","Jithu",null,"F"),
(63,"Conjoint","PONNAMKUDAM","Babumon",null,"M"),
(63,"Enfant",null,"Jovio","06","M"),
(63,"Enfant",null,"Anna Grace","04","F"),
(105,"Demandeur","HAJJEM","Salwa",null,"F"),
(105,"Conjoint","GUEDRI","Neji",null,"M"),
(105,"Enfant",null,"Mohamed","11","M"),
(105,"Enfant",null,"Ahmed","09","M"),
(105,"Enfant",null,"Takwa","07","F"),
(105,"Enfant",null,"Youssef","04","M"),
(105,"Enfant",null,"Hanen","01","F"),
(68,"Demandeur","EL MEFTAH","Fatiha",null,"F"),
(68,"Conjoint","AMIRI","Bachir",null,"M"),
(68,"Enfant",null,"Douae","09","F"),
(68,"Enfant",null,"Anas","06","M"),
(65,"Demandeur","THANASEKARAM","Jeyakala",null,"F"),
(65,"Conjoint","KUNARATNAN","Sureshkumar",null,"M"),
(65,"Enfant",null,"Kethusha","10","M"),
(65,"Enfant",null,"Kabeess","08","M"),
(65,"Enfant",null,"Birajesz","04","M"),
(106,"Demandeur","PIRATHEEPAN","Jeyamathy",null,"F"),
(106,"Conjoint","KRISHNASAMY","Piratheepan",null,"M"),
(106,"Enfant",null,"Ashwin","11","M"),
(106,"Enfant",null,"Anshika","06","F"),
(107,"Demandeur","KARUPIAH","Umadevi",null,"F"),
(107,"Enfant",null,"Darsann","15","M"),
(107,"Enfant",null,"Rosan","10","M"),
(103,"Demandeur","BARA","Laila",null,"F"),
(103,"Conjoint","MEGUENI","Annar",null,"M"),
(103,"Enfant",null,"Mohamed","15","M"),
(103,"Enfant",null,"Sabrina","03","F"),
(103,"Enfant",null,"Maria","10","F"),
(103,"Enfant",null,"Serine","05","F"),
(109,"Demandeur","JERIBI","Houda",null,"F"),
(109,"Conjoint","TAYEB","Arafat",null,"M"),
(109,"Enfant",null,"Rahma","08","F"),
(109,"Enfant",null,"Ahmad","06","M"),
(109,"Enfant",null,"Yusuf","02","M"),
(110,"Demandeur","EL MOUMNI","Fadwa",null,"F"),
(110,"Conjoint","ENNAIFER","Walid",null,"M"),
(110,"Enfant",null,"Hafsa","10","F"),
(110,"Enfant",null,"Ibrahim","09","M"),
(110,"Enfant",null,"Sirine","08","F"),
(112,"Demandeur","CHOUKOD","Zakia",null,"F"),
(112,"Enfant",null,"Raghad","07","F"),
(112,"Enfant",null,"Yassmine","05","F"),
(108,"Demandeur","FEREDE ALEMTSE MAI","Moyesha",null,"F"),
(108,"Enfant",null,"Solomun Mag.","02","F"),
(108,"Enfant",null,"Solomun Mart.","02","F"),
(111,"Demandeur","YOGESWARY","Thilleinathan",null,"F"),
(111,"Conjoint","VYKUNTHARAJAH","Manickaeeinathan",null,"M"),
(111,"Enfant",null,"Mayurikka","18","F"),
(111,"Enfant",null,"Pavurnigcaa","08","F"),
(111,"Enfant",null,"Heethjanan","04","M"),
(113,"Demandeur","ADAM","Tagried",null,"F"),
(113,"Enfant",null,"Majid","01","M"),
(113,"Enfant",null,"Mohamed","04","M"),
(113,"Enfant",null,"Moayad","8.25e-24 mois","M"),
(114,"Demandeur","EL MISRY","Karima",null,"F"),
(114,"Conjoint","AL KANTARI","Sidi Mohamed",null,"M"),
(114,"Enfant",null,"Romaysae","14","F"),
(114,"Enfant",null,"Rayane","09","M"),
(115,"Demandeur","SAHAYAPALAN","Sahayavenothini",null,"F"),
(115,"Enfant",null,"Anuja","17","F"),
(115,"Enfant",null,"Aswin","10","M"),
(115,"Enfant",null,"Aravinth","08","M"),
(116,"Demandeur","NWAMADI","Patience Amaka",null,"F"),
(116,"Conjoint","NWAMADI","Henry Rumi",null,"M"),
(116,"Enfant",null,"Valerie Oj.","10","F"),
(116,"Enfant",null,"Varrick Oj.","08","M"),
(116,"Enfant",null,"Valencia","04","F"),
(116,"Enfant",null,"Varen","02","M"),
(117,"Demandeur","NITHI YAANANTHALINGAM","Mathumitha",null,"F"),
(117,"Conjoint","THARMASENAPATHY","Visulincan",null,"M"),
(117,"Enfant",null,"Thevakain","12","M"),
(117,"Enfant",null,"Kereesan","11","M"),
(117,"Enfant",null,"Aarani","07","F"),
(62,"Demandeur","DAMIRI","Wafa",null,"F"),
(62,"Enfant",null,"Rayane","6 mois","M"),
(62,"Enfant",null,"Malak","03","F"),
(62,"Enfant",null,"Sabrine","14","F"),
(62,"Enfant",null,"Adam","15","M"),
(118,"Demandeur","ELMONI","Hebatalla",null,"F"),
(118,"Enfant",null,"Saleh","05","M"),
(118,"Enfant",null,"Shahd","02","F"),
(120,"Demandeur","DWARAKARATH","Pushkarani",null,"F"),
(120,"Conjoint","SUNDARAMOORTHY","Wignarajah",null,"M"),
(120,"Enfant",null,"Thurithigha","16","F"),
(120,"Enfant",null,"Mydli","11","F"),
(121,"Demandeur","THANGARAJAH","Gayathry",null,"F"),
(121,"Conjoint","PONNAMPALAM","Suntharamoorthy",null,"M"),
(121,"Enfant",null,"Dhooya","09","F"),
(121,"Enfant",null,"Neya","06","F"),
(121,"Enfant",null,"Shuban","03","M"),
(64,"Demandeur","SANGARALINGAM","Thillaikumaran",null,"M"),
(64,"Conjoint","REJFOLD RAVEENDRAN","Suventhiny",null,"F"),
(64,"Enfant",null,"Gabriel","04","M"),
(64,"Enfant",null,"Sandria","02","F"),
(119,"Demandeur","THIRUCHELVAM","Nirmalin Ida",null,"F"),
(119,"Conjoint","PARNABAS","Remond",null,"M"),
(119,"Enfant",null,"Recibha","03","F"),
(119,"Enfant",null,"Renoshan","4 mois","M"),
(122,"Demandeur","RASIAH","Kuhaneswary",null,"F"),
(122,"Conjoint","NAVARATNAM","Yogarajah",null,"M"),
(122,"Enfant",null,"Shaginth","14","M"),
(122,"Enfant",null,"Bathushan","13","M"),
(122,"Enfant",null,"Sagastiya","10","F"),
(126,"Demandeur","SINNIAH","Vasanthamalar",null,"F"),
(126,"Conjoint","SELLAKANDU","Muralitharan",null,"M"),
(126,"Enfant",null,"Anothan","09","M"),
(126,"Enfant",null,"Jabi Sana","15","F"),
(70,"Demandeur","CHANDRAKUMAR","Tasenthe",null,"F"),
(70,"Conjoint","KRISHNAPILLAI","Jeyaraj",null,"M"),
(70,"Autre","MANKUDDY","Kalimmai (69)",null,"F"),
(70,"Enfant",null,"Taniska","08","F"),
(70,"Enfant",null,"Rucksia","05","F"),
(70,"Enfant",null,"Jairish","18 mois","M"),
(123,"Demandeur","SOIRES","Cintia",null,"F"),
(123,"Conjoint","SAAD","Adib",null,"M"),
(123,"Enfant",null,"Adam","09","M"),
(123,"Enfant",null,"Mayanna","10","F"),
(124,"Demandeur","TAGHANE","Selma",null,"F"),
(124,"Conjoint","MERROUCHE","Billel",null,"M"),
(124,"Enfant",null,"Adem","09","M"),
(124,"Enfant",null,"Youcef","10","M"),
(125,"Demandeur","TARZOLT","Soumeya",null,"F"),
(125,"Conjoint","HAMMOUCHE","Abdelaziz",null,"M"),
(125,"Enfant",null,"Rokia","04","F"),
(125,"Enfant",null,"Abderrahman","02","M"),
(125,"Enfant",null,"Abdeldjalil","01","M"),
(127,"Demandeur","BEN EL BACHIR","Zahra",null,"F"),
(127,"Conjoint","FANGACHI","Mohamed",null,"M"),
(127,"Enfant",null,"Oumaima","17","F"),
(127,"Enfant",null,"Ali","13","M"),
(127,"Enfant",null,"Hafsa","11","F"),
(127,"Enfant",null,"Adam","08","M"),
(128,"Demandeur","LINGARATNAM","Pathmalatha",null,"F"),
(128,"Conjoint","VELAUTHAM","Raveendran",null,"M"),
(128,"Enfant",null,"Sugivan","15","M"),
(128,"Enfant",null,"Jasika","10","F"),
(128,"Enfant",null,"Labina","06","F"),
(129,"Demandeur","JEYACHANDRAN","Kayaledchuny",null,"F"),
(129,"Conjoint","BALACHANDRAN","Jeychandran",null,"M"),
(129,"Enfant",null,"Nathushan","10","M"),
(129,"Enfant",null,"Jenisha","13","F"),
(130,"Demandeur","JEGASOTHY","Rasavathani",null,"F"),
(130,"Conjoint","ARULIAH","Arul Rasa",null,"M"),
(130,"Enfant",null,"Rajeen","14","M"),
(130,"Enfant",null,"Kinicha","12","F"),
(130,"Enfant",null,"Thineshvin","09","M"),
(131,"Demandeur","ELAKMANATHAS","Priya",null,"F"),
(131,"Conjoint","SANDRALINGAM","Sandramohan",null,"M"),
(131,"Enfant",null,"Mithoona","08","F"),
(131,"Enfant",null,"Thujana","04","F"),
(67,"Demandeur","AUGUSTINE","Thomas",null,"M"),
(67,"Conjoint","JOSEPH","Leena",null,"F"),
(67,"Enfant",null,"Evelyn","03","F"),
(67,"Enfant",null,"Amondo","09","M"),
(132,"Demandeur","RAJARATNARATNAM","Murugavel",null,"M"),
(132,"Conjoint","KANAGASABAPATHY","sabananthini",null,"F"),
(132,"Enfant",null,"Senthan","05","M"),
(132,"Enfant",null,"Thanikhan","03","M"),
(66,"Demandeur","THANABALASINGHAM","Niruja",null,"F"),
(66,"Conjoint","KARAGARATNAM","Prabakaran",null,"M"),
(66,"Enfant",null,"Thackshikka","05","F"),
(66,"Enfant",null,"Vithusha","07","F"),
(133,"Demandeur","SHIJO","Bincy",null,"F"),
(133,"Enfant",null,"Anand","10","M"),
(133,"Enfant",null,"Alan","06","M");